#THIS IS THE SERVER WEBISTE/DISCORD YOU WANT TO FORWARD TO
Servername: '"Discord link/website"'
#
#THIS IS YOUR TICKET COMMAND YOU HAVE IN YOUR DISCORD SERVER
#FOR YOUR TICKET BOT
Ticketcommand: '"ticket command"'